import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./ui/components/Header";
import Footer from "./ui/components/Footer";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const isLogin = cookieStore.has("authjs.session-token");

  // console.log(isLogin);
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header session={isLogin} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
