const users = [
  { id: 1, name: "User1", email: "user1@user.com", password: 123456 },
  { id: 2, name: "User2", email: "user2@user.com", password: 123456 },
];

const blogs = [
  {
    id: 1,
    title: "A detailed step by step guide to manage your lifestyle",
    description: "Lorem Ipsum is simply dummy text of the printing and typeset",
    date: "2024-01-20",
    category: "Lifestyle",
    author: "Alex Bennett",
    user_id: 1,
  },
  {
    id: 2,
    title: "10 Tips for Healthy Eating",
    description: "Discover the best tips for maintaining a healthy diet.",
    date: "2024-06-16",
    category: "Health",
    author: "Sarah Connor",
    user_id: 2,
  },
  {
    id: 3,
    title: "Top Travel Destinations for 2024",
    description:
      "Explore the top travel destinations you must visit this year.",
    date: "2024-07-17",
    category: "Travel",
    author: "John Doe",
    user_id: 2,
  },
  {
    id: 4,
    title: "How to Stay Productive While Working from Home",
    description: "Tips and tricks to boost your productivity at home.",
    date: "2024-06-25",
    category: "Productivity",
    author: "Jane Smith",
    user_id: 2,
  },
  {
    id: 5,
    title: "The Ultimate Guide to Yoga for Beginners",
    description: "Start your yoga journey with this comprehensive guide.",
    date: "2024-04-24",
    category: "Fitness",
    author: "Emily Davis",
    user_id: 2,
  },
  {
    id: 6,
    title: "Financial Tips for Millennials",
    description: "Learn how to manage your finances effectively.",
    date: "2024-07-06",
    category: "Finance",
    author: "Michael Johnson",
    user_id: 2,
  },
  {
    id: 7,
    title: "Home Decor Trends for 2024",
    description: "Get inspired by the latest home decor trends.",
    date: "2023-05-14",
    category: "Home",
    author: "Laura Wilson",
    user_id: 2,
  },
  {
    id: 8,
    title: "The Best Workout Routines for Busy People",
    description: "Stay fit with these quick and effective workout routines.",
    date: "2024-05-06",
    category: "Fitness",
    author: "Chris Lee",
    user_id: 1,
  },
  {
    id: 9,
    title: "How to Cultivate a Growth Mindset",
    description: "Unlock your potential with a growth mindset.",
    date: "2024-07-19",
    category: "Personal Development",
    author: "Patricia Brown",
    user_id: 1,
  },
  {
    id: 10,
    title: "The Importance of Mental Health Awareness",
    description: "Understand the importance of mental health and well-being.",
    date: "2024-07-25",
    category: "Health",
    author: "Robert Green",
    user_id: 1,
  },
  {
    id: 11,
    title: "A Beginner's Guide to Meditation",
    description: "Learn how to start meditating with this beginner's guide.",
    date: "2024-07-03",
    category: "Wellness",
    author: "Linda Martinez",
    user_id: 1,
  },
];

module.exports = { users, blogs };
